TOP_DIR = ..

USER_LIB = cm

USER_SRCS = CMBuffer.cpp \
			CMEpoll.cpp \
			CMEpollWrapper.cpp \
			CMListen.cpp \
			CMRequest.cpp \
			CMResponse.cpp \
			CMSession.cpp \
			CMSessionId.cpp \
			CMSocketHelp.cpp \
			CMStream.cpp \
			CMTaskThread.cpp \
			CMTimerQueue.cpp \

USER_INCLDIRS = -I$(TOP_DIR)/include

USER_DEFFLAGS = -g -lpthread -std=c++0x

USER_LINK_DLLS = -lpthread

USER_LINK_LIBS = 

USER_OBJ_DIR = $(TOP_DIR)/obj/
USER_LIB_DIR = $(TOP_DIR)/lib/

include $(TOP_DIR)/makeinclude/makeinclude